### ISSUE TITLE
Docker Command creates an outdated instance

### ISSUE THREAD

**Issue by ericsche** [Tysonpower/starlinkstatus#25]
Hey!
Noticed that my Station was outdate so I scraped it and created a new one using the docker command but I still get the Oudated signal.

Is this expected ?

FYI : https://starlinkstatus.space/stations/556

**Comment by Tysonpower** [comment]
Thx :)

Should be fixed now, the other contributer used the wrong .sh url to build the docker image.

**Comment by Tysonpower** [comment]
please recreate the docker installation and let me know if it works now

**Comment by Tysonpower** [comment]
@ericsche Did you test the updated code?

**Comment by ericsche** [comment]
Hey! Sorry was not at home during the weekend, just killed and created an instance with the new docker file and still having the same issue (waited 2 test just to be sure) :(

**Comment by Tysonpower** [comment]
yeah all good on my site, just a lot of todos on my dayjob :) WIll have a look at the docker image later/tomorrow.

**Comment by Tysonpower** [comment]
@ericsche just tested it and all works fine, the new v1.2 script is used to build the docker image. Please make sure to delete the build docker image as well as all other data related to it before you try to compose it again.
